Trash_Collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

Trash_Collector/employees/urls.py
from django.urls import path
from . import views

# TODO: Determine what distinct pages are required for the user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('<int:customer_id>/confirm/', views.confirm, name='confirm'),
    path('filter/', views.filter, name='filter')
]

Trash_Collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding Django's built in routes (login and logout). Notice there is no 'login' function in accounts/views.py. Django takes care of this for us.
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate trach_collector/views.py for more info
    path('', views.group_redirect, name='home')
]

Trash_Collector/employees/models.py
from django.db import models

# Create your models here.

# TODO: Create an Employee model with properties required by the user stories

class Employee(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)
    zip_code = models.CharField(max_length=50)

Trash_Collector/employees/views.py
from django.db.models.fields.related import ForeignKey
from django.http import HttpResponse
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.apps import apps
from datetime import date
import calendar
from django.core.exceptions import ObjectDoesNotExist
from .models import Employee
from django.contrib.auth.decorators import login_required


# Create your views here.

# TODO: Create a function for each path created in employees/urls.py. Each will need a template as well.

@login_required
def index(request):
    # This line will get the Customer model from the other app, it can now be used to query the db for Customers
    Customer = apps.get_model('customers.Customer')
    logged_in_user = request.user
    weekdays = list(calendar.day_name)

    try:
        # This line will return the customer record of the logged-in user if one exists
        logged_in_employee = Employee.objects.get(user=logged_in_user)
        content_present = True
        today = date.today()
        weekday = weekdays[date.today().weekday()]
        customer_data = Customer.objects.filter(zip_code=logged_in_employee.zip_code)
        customer_data = customer_data.exclude(suspend_start__lt=today, suspend_end__gte=today) 
        if len(list(customer_data)) == 0:
            content_present = False
        context = {
            'logged_in_employee': logged_in_employee,
            'today': today,
            'customer_data': customer_data,
            'content_present': content_present,
            'weekday': weekday,
        }
        return render(request, 'employees/index.html', context)
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('employees:create'))

@login_required
def create(request):
    logged_in_user = request.user 
    if request.method == 'POST':
        name_from_form = request.POST.get('name')
        zip_from_form = request.POST.get('zip_code')
        new_employee = Employee(name=name_from_form, user=logged_in_user, zip_code=zip_from_form)
        new_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        return render(request, 'employees/create.html')

@login_required
def edit_profile(request):
    logged_in_user = request.user
    logged_in_employee = Employee.objects.get(user=logged_in_user)
    if request.method == "POST":
        name_from_form = request.POST.get('name')
        zip_from_form = request.POST.get('zip_code')
        logged_in_employee.name = name_from_form
        logged_in_employee.zip_code = zip_from_form
        logged_in_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        context = {
            'logged_in_employee': logged_in_employee
        }
        return render(request, 'employees/edit_profile.html', context)        

@login_required
def confirm(request, customer_id):
    Customer = apps.get_model('customers.Customer')
    customer_data = Customer.objects.get(pk= customer_id)
    customer_data.date_of_last_pickup = date.today()
    customer_data.balance = (customer_data.balance + 20)
    customer_data.one_time_pickup = None
    customer_data.save()
    return HttpResponseRedirect(reverse('employees:index'))
    if request.method == "GET":
        return render(request, 'employees:index')
 
@login_required
def filter(request):
    Customer = apps.get_model('customers.Customer')
    logged_in_user = request.user
    logged_in_employee = Employee.objects.get(user=logged_in_user)
    customer_data = Customer.objects.filter(zip_code=logged_in_employee.zip_code)
    weekdays = list(calendar.day_name)
    weekday = weekdays[date.today().weekday()]
    if request.method == 'POST':
        weekday = request.POST.get('weekday')
        context = {
            'customer_data': customer_data,
            'weekday': weekday
        }
        return render(request, 'employees/filter.html', context)
    else:    
        context = {
            'customer_data': customer_data,
            'weekday': weekday
        }
    return render(request, 'employees/filter.html', context)

Trash_Collector/employees/templates/employees/create.html
{% extends 'base.html' %}

{% block title %} Employee Create {% endblock %}

{% block header %} Please Complete Registration {% endblock %}

{% block content %}

<form action="{% url 'employees:create' %}" method="post">
    {% csrf_token %}
    Name: <input type="text" name="name" id="name"><br />
    Zip Code: <input type="text" name="zip_code" id="zip_code"><br />
    <input type="submit" value="Register">
</form>

{% endblock %}

Trash_Collector/employees/templates/employees/edit_profile.html
{% extends 'employees\employee_base.html' %}

{% block title %} Employee Profile Edit {% endblock %}

{% block header %} <h2 class='text-primary'>Update Your Information </h2> {% endblock %}

{% block content %}
<br />
<form action="{% url 'employees:edit_profile' %}" method="post">
    {% csrf_token %}
    Name: <input type="text" name="name" id="name" value="{{logged_in_employee.name}}">
    <br />
    <br />
    Zip Code: <input type="text" name="zip_code" id="zip_code" value="{{logged_in_employee.zip_code}}">
    <br />
    <br />
    <input class='btn btn-primary' type="submit" value="Submit">
</form>

{% endblock %}

Trash_Collector/employees/templates/employees/employee_base.html
{% extends 'base.html' %}

{% block navbar %}
<a class="nav-item nav-link" href="{% url 'employees:index' %}">Home</a>
    <a class="nav-item nav-link" href="{% url 'employees:edit_profile' %}">Edit Profile</a>
    <a class="nav-item nav-link" href="{% url 'employees:filter' %}">Filter Pick-Up</a>
{% endblock %}

Trash_Collector/employees/templates/employees/filter.html
{% extends 'employees\employee_base.html' %}

{% block title %}{% block header %} Filter Date {% endblock %}{% endblock %}

{% block content %}
<div>
        <header class='text-success'>Filtered Day selected: {{ weekday }}</header>
        <br>
        <h3 class='text-primary'>Please select a Day of the Week</h3> <br>
        <form action="{% url 'employees:filter' %}" method="post">
            {% csrf_token %}
            <select class='selectpicker' name='weekday' id='weekday' placeholder="{{weekday}}">
                <option value='Monday'>Monday</option>
                <option value='Tuesday'>Tuesday</option>
                <option value='Wednesday'>Wednesday</option>
                <option value='Thursday'>Thursday</option>
                <option value='Friday'>Friday</option>
                <option value='Saturday'>Saturday</option>
                <option value='Sunday'>Sunday</option>
            </select>
            <input class='btn btn-primary' type="submit" value="Load">
        <h2 class='text-primary'>Pickups for the Selected Day:</h2>
        <div class='row'>
        {% for customer in customer_data %}
            {% if customer.weekly_pickup == weekday %}
            <div class='card col-4'>
                <h3 class='card-header'>{{ customer.name }}</h3>
                <p class='card-body'>Address: {{ customer.address}}</p>
                <p class='card-footer'></p>
            </div>
            {% endif %}
        {%endfor%} 
        </div>
        <br>   
</div>
{% endblock %}

Trash_Collector/employees/templates/employees/index.html
{% extends 'employees\employee_base.html' %}

{% block title %}{% block header %} Employee Home {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    Hello Employee {{ logged_in_employee.name }}! Your working in Zone: {{ logged_in_employee.zip_code}} <br />
    Todays date is {{ weekday }}, {{ today }} <br>
    {% if content_present == False %}
      <h3 class='row'>No Customers Today! Nice work!</h3>
    {% endif %}
    <br>
    <br>
    <h2 class='text-primary'>Pick Up's for Today:</h2> <br>
    <div class='row'>
    {% for customer in customer_data %}
      {% if customer.weekly_pickup == weekday and customer.date_of_last_pickup != today %}
        <div class='card col-4'>
          <h3 class='card-header'>{{ customer.name }}</h3>
          <p class='card-body'>Address: {{ customer.address}}</p>
          <div class='card-footer'>
          <a class=' btn btn-primary' href="{% url 'employees:confirm' customer.id %}">Confirm Pick Up</a>
          </div>
        </div>
      {% endif %}
    {% endfor %}
    </div>
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}